config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  namespace :admin do
    resources :users
    resources :comments
    resources :communities
    resources :links
    resources :posts
    resources :topics

    root to: "users#index"
  end

  root 'home#index'

  get 'home/index'

  get 'go/:id', to: 'posts#show'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts do
    resources :comments
    member do
      post :vote
    end
  end
  resources :communities do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :links
  resources :topics
  resources :u, controller: 'users' do
    resources :comments, except: [:index]
    get 'comments', to: 'comments#user_comments'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_ancestry
  
    belongs_to :user
    belongs_to :post
  
    validates :text, presence: true
  
    after_commit :create_notifications, on: [:create]
  
    def create_notifications
      Notification.create(
        notify_type: 'comment',
        actor: self.user,
        user: self.post.user,
        target: self
      )
    end
  end
  

app/controllers/admin/comments_controller.rb
module Admin
  class CommentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find_by_id(params[:parent_id])
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.ancestry = params[:comment][:parent_id]
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@post)
      flash[:notice] = t('comment.create.success')
    else
      redirect_to post_path(@post)
      flash[:notice] = @comment.errors.messages.values[0]
    end
  end

  def user_comments
    @user = User.find_by_id(params[:u_id])
    @comments = @user.comments.where(ancestry: nil)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def nested_comments(comments)
        comments.map do |comment, sub_comments|
            render(comment) + content_tag(:div, nested_comments(sub_comments), class: 'nested_comments')

        end.join.html_safe
    end
end

app/views/comments/_comment.html.erb
<div class="listItem comment row">
	<div class="postQuestion col-md-12">
		<div class="postDetails ">
			<ul>
				<li class="pull-right">
					<span><%= link_to comment.user.email,  u_path(@post.user)%> </span>
				</li>
				<li class="pull-right">
					<i class="glyphicon glyphicon-time"></i>
					<%= comment.created_at %>
				</li>
				<li class="pull-right">
					<i class="glyphicon glyphicon-time"></i>
					<%= link_to t('.reply'), new_post_comment_path(@post, :parent_id => comment) %>
				</li>
			</ul>
		</div>
		</br></br>
		<div>
			<%= comment.text %>
		</div>
	</div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1><%= t('.heading') %></h1>
<div class="itemsList">
	<%= render @comment %>
</div>

<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <%= form.hidden_field(:parent_id, {value: params[:parent_id]}) %>
  <p>
    <%= form.text_area :text, {placeholder: true, :class=>'text_area'}%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/user_comments.html.erb
<%= render 'users/user_profile' %>
<h2 class="inline"><%= link_to t('.my_posts'),  u_path(params[:u_id]) %>  |  </h1>
<h2 class="inline"><%=  t('.my_comments') %></h1>
<div class="content container">
  	<div class="itemsList">
  		<% if @comments.any? %>
  			<% @comments.each do |comment| %>
		  		<div class="listItem comment row">
					<div class="postQuestion col-md-12">
						<div class="postDetails ">
							<ul>
								<li class="pull-right">
									<span><%= link_to comment.user.email,  u_path(comment.post.user)%> </span>
								</li>
								<li class="pull-right">
									<i class="glyphicon glyphicon-time"></i>
									<%= comment.created_at %>
								</li>
								<li class="pull-right">
									<i class="glyphicon glyphicon-time"></i>
									<%= link_to t('.reply'), new_post_comment_path(comment.post, :parent_id => comment) %>
								</li>
							</ul>
						</div>
						</br></br>
						<div>
							<%= comment.text %>
						</div>
					</div>
				</div>
			<% end %>
		<% else %>
			<div class="listItem row">
		  		<h2><%= t('.nil') %></h2>
		  	</div>
		<% end %>
  	</div>
</div>
</br>