config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  namespace :admin do
    resources :users
    resources :comments
    resources :communities
    resources :links
    resources :posts
    resources :topics

    root to: "users#index"
  end

  root 'home#index'

  get 'home/index'

  get 'go/:id', to: 'posts#show'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts do
    resources :comments
    member do
      post :vote
    end
  end
  resources :communities do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :links
  resources :topics
  resources :u, controller: 'users' do
    resources :comments, except: [:index]
    get 'comments', to: 'comments#user_comments'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :post
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_moderator, only: [:edit, :update]

  def new
    @topic = Topic.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      @topic = Topic.new(topic_params)
      @topic.post = @post
      if @topic.save
        redirect_to @post
      else
        render :new
      end
    else
      @topic.save
      render :new
    end
  end

  def edit
    @topic = Topic.find_by_id(params[:id])
  end

  def update
    @topic = Topic.find_by_id(params[:id])
    if @topic.update(topic_params)
      redirect_to @topic.post
    else
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:text)
  end

  def post_params
    params.require(:topic).permit(:community_id, :title)
  end

  def authenticate_moderator
    redirect_to root_path, notice: t('not_authorized') unless current_user && current_user.moderator?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1><%= t '.heading' %></h1>

<%= form_with scope: :topic, url: topic_path, method: "put" ,local: true do |form| %>
	<% if @topic.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @topic.errors.messages.values.each do |msg| %>
          <%msg.each do  |m| %>
            <li><%= m %></li>
          <%end %>
        <% end %>
      </ul>
    </div>
  	<% end %>
  <%= hidden_field_tag "topic_id", "#{@topic.id}" %>
  <p>
    <%= form.text_area :text , {:class=>'text_area'}%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/topics/new.html.erb
<h1><%= t '.heading' %></h1>

<%= form_with scope: :topic, url: topics_path, local: true do |form| %>
	<% if @topic.errors.any?%>
    <div id="error_explanation">
      <ul>
        <% @post.errors.messages.values.each do |msg| %>
	        <%msg.each do  |m| %>
	          <li><%= m %></li>
	        <%end %>
      	<% end %>
        <% @topic.errors.messages.values.each do |msg| %>
          <%msg.each do  |m| %>
            <li><%= m %></li>
          <%end %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.collection_select :community_id, Community.order(:name),:id,:name, {prompt: t('.select_community')}, {:class=>'collection_select'}%>
    <%= form.text_field :title, placeholder: true %>
    <%= form.text_area :text , {:class=>'text_area'}%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>