config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  namespace :admin do
    resources :users
    resources :comments
    resources :communities
    resources :links
    resources :posts
    resources :topics

    root to: "users#index"
  end

  root 'home#index'

  get 'home/index'

  get 'go/:id', to: 'posts#show'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts do
    resources :comments
    member do
      post :vote
    end
  end
  resources :communities do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :links
  resources :topics
  resources :u, controller: 'users' do
    resources :comments, except: [:index]
    get 'comments', to: 'comments#user_comments'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  acts_as_votable

  belongs_to :community
  belongs_to :user
  has_one :link
  has_one :topic
  has_many :comments

  def self.search(query)
    if query
      where('title LIKE :query', query: "%#{query}%")
    else
      all
    end
  end

  def normalize_friendly_id(string)
    string.gsub(/\s+/, '-').gsub(/[^a-zA-Z0-9أ-ي-]*/, '')
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def vote
    value = params[:type]
    @post = Post.friendly.find(params[:id])
    if value == 'up'
      @post.vote_by voter: current_user, vote: 'like', vote_scope: 'reputation', vote_weight: 1
    else
      @post.vote_by voter: current_user, vote: 'dislike', vote_scope: 'reputation', vote_weight: -1
    end
    redirect_to @post, notice: t('voting_thanks')
  end

  def index
    @posts = Post.search(params[:search])
  end

  def show
    @post = Post.friendly.find(params[:id])
    @comment = Comment.new
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="listItem row">
	<div class="post_vote col-md-1">
		<div>
			<%= link_to vote_post_path(post, type: "up"), method: "post" do %>
				<i class="glyphicon glyphicon-menu-up"></i>
			<% end %>
			<div class="post_points">
				<%= post.find_votes_for(:vote_scope => 'reputation').sum(:vote_weight) %>
			</div>
			<%= link_to vote_post_path(post, type: "down"), method: "post" do %>
				<i class="glyphicon glyphicon-menu-down"></i>
			<% end %>
		</div>
	</div>
	<div class="postQuestion col-md-11">
		<h2><%= link_to post.title, post_path(post) %></h2>
		<div class="postDetails ">
			<ul>
			    <li class="pull-right">
			    	<span><%= link_to post.user.email,  u_path(post.user)%> </span>
				</li>
		      	<li class="pull-right">
		      		<i class="glyphicon glyphicon-align-justify"></i>
		      		<%= link_to post.community.name,  community_path(post.community)%>
		        </li>
		    	<li class="pull-right">
		    		<i class="glyphicon glyphicon-time"></i>
		      		<%= post.user.created_at.strftime('%B %e %Y at %l:%M %p') %>
		    	</li>
		      	<li class="pull-right">
		      		<i class="glyphicon glyphicon-comment"></i>
		      		<%= link_to "#{post.comments.count} #{t('comment_count')} ", post_path(post) %>
		      	</li>
	  		</ul>
		</div>
	</div>
</div>

app/views/posts/_search.html.erb
<%= form_tag posts_path, method: "get" do %>
  <div class="btn-group">
    <%= text_field_tag :search, params[:search], id: 'searchinput' , :placeholder => t("serach_for") %>
    <a href="/"><span id="searchclear" class="glyphicon glyphicon-remove-circle"></span></a>
  </div>
  <%= submit_tag t("search"), :name => nil %>
<% end %>

app/views/posts/index.html.erb
<% if params[:search] %>
	<h1><%= t 'search_result' %><span><%= params[:search] %></span></h1>
<% else %>
	<h1><%= t '.all_posts' %></h1>
<% end %>
<%= render 'search' %>
<div class="content container">
	<div class="itemsList">
		<% if @posts.empty? %>
			<div class="listItem row">
				<h2><%= t '.nil_posts' %></h2>
			</div>
		<% else %>
			<%= render @posts %>
	  <% end %>
	</div>
</div>
</br>

app/views/posts/show.html.erb
<div class="content container">
	<div class="itemsList">
  		<div class="listItem post row">
  			<div class="post_vote col-md-1">
				<div>
					<%= link_to vote_post_path(@post, type: "up"), method: "post" do %>
						<i class="glyphicon glyphicon-menu-up"></i>
					<% end %>
					<div class="post_points">
						<%= @post.find_votes_for(:vote_scope => 'reputation').sum(:vote_weight) %>
					</div>
					<%= link_to vote_post_path(@post, type: "down"), method: "post" do %>
						<i class="glyphicon glyphicon-menu-down"></i>
					<% end %>
				</div>
			</div>
  			<div class="postQuestion col-md-11">
				<h2><%= link_to @post.title, post_path(@post) %></h2>
				<% if @post&.link %>
	  				<span><%= @post.link.url %></span>
	  			<% end %>
				<div class="postDetails ">
  					<ul>
					    <li class="pull-right">
					    	<span><%= link_to @post.user.email,  u_path(@post.user)%> </span>
						</li>
				      	<li class="pull-right">
				      		<i class="glyphicon glyphicon-align-justify"></i>
				      		<%= link_to @post.community.name,  community_path(@post.community)%>
				        </li>
				    	<li class="pull-right">
				    		<i class="glyphicon glyphicon-time"></i>
				      		<%= @post.user.created_at.strftime('%B %e %Y at %l:%M %p') %>
				    	</li>
				      	<li class="pull-right">
				      		<i class="glyphicon glyphicon-comment"></i>
				      		<%= @post.comments.count %> <%= t('comment_count') %>
				      	</li>
				      	<li class="pull-right dropdown">
				      		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
				      			<span>المزيد</span>
				      			<i class="glyphicon glyphicon-option-horizontal"></i>
				      		</a>
			                <ul class="dropdown-menu">
			                  <li>
			                   <a href="https://www.facebook.com/sharer/sharer.php?u=https://io.hsoub.com/go/<%= @post.id %>" target="_blank">
			                   	<i class="fab fa-facebook-f"></i><%= t('fb')%>
			                   </a>
			                  </li>
			                  <li>
			                   <a href="https://twitter.com/intent/tweet?text=<%= @post.title %>&via=HsoubIO&related=HsoubIO&url=https://io.hsoub.com/go/<%= @post.id %>" target="_blank">
			                   	<i class="fab fa-twitter"></i><%= t('twitter')%>
			                   </a>
			                  </li>
			                  <li>
			                   <a href="http://www.linkedin.com/shareArticle?mini=true&url=https://io.hsoub.com/go/<%= @post.id %>" target="_blank">
			                   	<i class="fab fa-linkedin"></i><%= t('linkedin')%>
			                   </a>
			                  </li>
			                  <li>
			                   <a href="/go/<%= @post.id %>" target="_blank">
			                   	<i class="fas fa-link"></i><%= t('short_link')%>
			                   </a>
			                  </li>
			                </ul>
				      	</li>
				      	<% if current_user && current_user.moderator? %>
  							<li class="pull-right">
  								<% if @post&.link %>
				      				<%= link_to t('.edit'), edit_link_path(@post) %>
	  							<% end %>
	  							<% if  @post&.topic %>
	  								<%= link_to t('.edit'), edit_topic_path(@post) %>
  								<% end %>
				      		</li>
						<% end %>
				  	</ul>
  				</div>
  				</br></br>
  				<div>
  					<% if  @post&.topic %>
	  					<%= @post.topic.text %>
  					<% end %>
  				</div>
  			</div>
  		</div>
  		<div class="listItem commentBox row">
  			<%= form_with(model: [ @post, @comment ], local: true) do |form| %>
			  <p>
			    <%= form.text_area :text , {placeholder: true, :class=>'text_area'}%>
			  </p>

			  <p>
			    <%= form.submit %>
			  </p>
			<% end %>
  		</div>
  		<h3><%= t '.comments' %></h3>
  		<% if @post.comments.any? %>
	  		<%= nested_comments @post.comments.arrange(:order => :created_at) %>
		<% else %>
		  	<p><%= t('.no_comments') %></p>
		<% end %>
	</div>
</div>
</br>
<%= link_to t('.back'), posts_path %>