config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  namespace :admin do
    resources :users
    resources :comments
    resources :communities
    resources :links
    resources :posts
    resources :topics

    root to: "users#index"
  end

  root 'home#index'

  get 'home/index'

  get 'go/:id', to: 'posts#show'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts do
    resources :comments
    member do
      post :vote
    end
  end
  resources :communities do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :links
  resources :topics
  resources :u, controller: 'users' do
    resources :comments, except: [:index]
    get 'comments', to: 'comments#user_comments'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ApplicationRecord
    has_many :posts
    has_many :follows
    has_many :users, through: :follows

    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/admin/communities_controller.rb
module Admin
  class CommunitiesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)

    if @community.save
      redirect_to @community
    else
      render :new
    end
  end

  def index
    @communities = Community.all
  end

  def show
    @community = Community.find_by_id(params[:id])
    @posts = @community.posts
  end

  def follow
    @community = Community.find_by_id(params[:id])
    current_user.follows.create(community: @community)
    redirect_to @community, notice: 'قمت بمتابعة المجتمع بنجاح'
  end

  def unfollow
    @community = Community.find_by_id(params[:id])
    current_user.follows.where(community: @community).first.destroy
    redirect_to @community, notice: 'قمت بإلغاء متابعة المجتمع بنجاح'
  end

  private

  def community_params
    params.require(:community).permit(:name, :description)
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/index.html.erb
<h1><%= t '.title' %></h1>
  	<div class="content container">
  		<div class="itemsList">
  			<% if @communities.empty? %>
  				<div class="listItem row">
  					<h2><%= t '.nil_communities' %></h2>
  				</div>
  			<% else %>
	  			<% @communities.each do |community| %>
		  			<h2><%= link_to community.name, community_path(community) %></h2>
				  <% end %>
			  <% end %>
  		</div>
  	</div>
</table>
</br>

app/views/communities/new.html.erb
<h1><%= t '.new_community' %></h1>

<%= form_with scope: :community, url: communities_path, local: true do |form| %>
	<% if @community.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @community.errors.messages.values.each do |msg| %>
	        <%msg.each do  |m| %>
	          <li><%= m %></li>
	        <%end %>
      	<% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.text_field :name, placeholder: true %>
  </p>
  <p>
    <%= form.text_area :description, {placeholder: true ,class: 'topic_text_area'}%>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/communities/show.html.erb
<h2><%= t '.title' %> <%= " " + @community.name %></h2>
<% unless current_user&.communities.include? @community %>
	<%= link_to t('follow'), follow_community_path(@community), method: :post, class: 'btn btn-success' %>
<% else %>
	<%= link_to t('unfollow'), unfollow_community_path(@community), method: :post, class: 'btn btn-danger' %>
<% end %>
<div class="content container">
	<div class="itemsList">
		<% if @posts.empty? %>
			<div class="listItem row">
				<h2><%= t '.nil_posts' %></h2>
			</div>
		<% else %>
			<%= render @posts %>
		<% end %>
	</div>
</div>
</br>